mangotreedev/mangotree-website

package-lock.json, package.json, src/css/styles/siteStyle.scss, src/css/styles/themeColors.scss, src/index.html
Added all the styles (font sizes, line heights, and colors) used in Figma to build the prototype. Had to import a bolder font of 'Lato' because the builtin 'Lato' bold is thinner. 
=> Base Styles Configuration

src/css/components/partnerscroll.scss, src/css/components/siteComponents.scss, src/css/pages/contactPage.scss, src/css/pages/partnerPage.scss, src/css/pages/sitePages.scss, src/css/styles/generalStyle.scss, src/index.html
Horizontal sliding component for partners
=> Build past partners page

src/css/components/horizontalScrollingWrapper.scss, src/css/components/partnerscroll.scss, src/css/components/siteComponents.scss, src/css/components/teamscroll.scss, src/css/pages/partnerPage.scss, src/css/pages/scrollWrapperPage.scss, src/css/pages/sitePages.scss, src/index.html
=> Build team page

src/css/components/portfolioScroll.scss, src/css/components/siteComponents.scss, src/css/pages/dist/portfolioPage.css, src/css/pages/dist/scrollWrapperPage.css, src/css/pages/portfolioPage.scss, src/index.html, src/js/components/dist/init_left_scroll.dev.js, src/js/components/dist/init_scroll_project.dev.js, src/js/components/init_left_scroll.js, src/js/dist/index.dev.js, src/js/index.js
- Finished project's page, we just need to change the pictures, text and tags for what we want
=> Projects page

src/css/styles/_general-mqueries.scss, src/css/styles/site-style.scss, src/index.html
Added media query and html structure for mobile responsiveness
=> Build responsive structure

src/css/components/_partner-list.scss, src/css/components/_partner-scroll.scss, src/css/components/_titles.scss, src/css/components/site-components.scss, src/css/pages/_partner-page.scss, src/css/styles/_general-style.scss, src/index.html
Built partner page for desktop size, no scroll for now
=> Build browser partner page

src/css/components/_team-transition.scss, src/css/components/_titles.scss, src/css/components/site-components.scss, src/css/pages/_team-page.scss, src/css/pages/site-pages.scss, src/index.html, src/js/components/init_team_transitions.js, src/js/index.js
=> Build browser team page

src/css/components/_buttons.scss, src/css/components/_skills-display.scss, src/css/components/site-components.scss, src/css/pages/_skills-page.scss, src/index.html, src/js/components/init_skills_float.js, src/js/index.js
Build team skills page, need to tweak some animations still
=> Build browser skill page

src/css/components/_navbar.scss, src/index.html, src/js/components/init_hide_navbar.js, src/js/components/init_konami_code.js, src/js/index.js
- Added browser navbar that hides on scroll down
- Added white MangoTree icon for Konami code
=> Browser navbar

src/index.html, src/js/components/init_konami_code.js
Added some todos to the website to talk about tomorrow
Small konami code fix
=> Add todo comments

src/css/components/_burger-icon.scss, src/css/components/_buttons.scss, src/css/components/_portfolio-scroll.scss, src/css/pages/_responsive-overlay.scss, src/css/pages/site-pages.scss, src/css/styles/_general-style.scss, src/index.html, src/js/components/init_konami_code.js
Small fixes, please see commits for reference
=> Small fixes p3

src/css/styles/_general-style.scss, src/index.html
=> FIX: Imported additional font characters

src/css/components/_buttons.scss, src/css/components/_portfolio-card.scss, src/css/components/_skills-display.scss, src/css/components/_team-transition.scss, src/css/pages/_team-page.scss, src/index.html, src/js/components/init_design_text.js, src/js/components/init_skills_float.js, src/js/index.js
- Fixed iPad responsiveness for what we do
- Fixed desktop our team animation breaking boundaries
- Fixed our skills iPad version
- Fixed red markers replacing arrows in mobile in our team
=> Small fixes p6

src/css/components/_buttons.scss, src/css/components/_navbar.scss, src/index.html, src/js/components/init_navbar.js
Added in feedback from five different sources as todos
=> Response fixes 1

src/404.html, src/css/components/_konami-code.scss, src/css/components/_navbar.scss, src/css/components/_skills-scroll.scss, src/css/pages/_landing-page.scss, src/index.html, src/js/components/init_define_btn.js, src/js/components/init_design_text.js, src/js/components/init_konami_code.js, src/js/components/init_navbar.js, src/js/components/init_sound_icons.js, src/js/components/init_video_modal.js, webpack.config.js
Value proposition work + minor bug fixes
404 page
=> Response fixes 2

src/index.html
- Dropped LinkedIn link
- Move what we do and our team before portfolio
=> Final fixes

src/css/components/_buttons.scss, src/css/components/_navbar.scss, src/css/components/_partner-list.scss, src/css/components/_partner-scroll.scss, src/index.html, src/js/components/init_skills_float.js
See commits for the changes made.
Not all changes recommended by Marty implemented ex: carinspect tablet fix because of cost and minimal impact
=> Marty fixes

src/index.html, src/js/components/init_landing_transitions.js
Switched order for skills
Added scroll trigger for define button
Added gatezero video
Change meta tags
=> Gate zero fixes

src/index.html, src/js/components/init_drawing_trigger.js, src/js/components/init_landing_transitions.js
Fix define bug btn
Fix contact btn bug
=> Final tweaks

src/css/components/_buttons.scss, src/js/components/init_landing_transitions.js
- Fixed disappearing mango when clicked and scrolling
- Fixed skills text jumping to next line on Macbook display
=> Scroll fix

src/index.html
=> FEAT: Dropped in google site tag

src/index.html
=> FEAT: Added google tag manager to main page

src/css/components/_video-modal.scss, src/index.html
Fixed the bug that didn't allow you to scroll horizontally
=> FIX: Fixed modal bug on scroll

package-lock.json, src/index.html, yarn.lock
Update instamove info and video
=> Update instamove info
